import type { Metadata } from "next";
import { Geist, Geist_Mono,Lora, Raleway } from "next/font/google";
// örneğin layout.tsx veya layout.js içinde




import "./globals.css";
import { Toaster } from "react-hot-toast"; // ✅ toast bileşeni

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
});

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${lora.variable} ${raleway.variable}antialiased`}>
        {children}
        <Toaster /> {/* ✅ toast mesajları burada görünür */}
      </body> 
    </html>
  );
}